title: Today I Learned
description: A collection of concise write-ups on small things I learn day to day
theme: minima
author: naiksharat

# Build settings
markdown: kramdown
permlink: pretty

# Theme settings
minima:
  header_pages: []

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
